spring.application.name=demo
server.port=8082
management.endpoints.web.exposure.include=health
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.xhtml
spring.thymeleaf.mode=HTML

spring.datasource.url=jdbc:oracle:thin:@ptlisdev02.epimetheus.pt:1521:PTLISDEV02
spring.datasource.username=DPM_MD
spring.datasource.password=DPM2MD
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.properties.eclipselink.target-database=Oracle
spring.jpa.properties.eclipselink.weaving=false

spring.jpa.properties.eclipselink.logging.level.sql=FINE
spring.jpa.properties.eclipselink.logging.parameters=true

logging.level.org.eclipse.persistence.jpa=INFO
logging.level.org.eclipse.persistence.logging.sql=INFO

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000

spring.jpa.show-sql=false


spring.sql.init.mode=never

spring.datasource.hikari.maxLifetime=0
spring.datasource.hikari.idleTimeout=0
spring.datasource.hikari.keepaliveTime=0

logging.level.org.springframework.jdbc.core=OFF
logging.level.org.springframework.jdbc.core.JdbcTemplate=OFF
logging.level.org.springframework.jdbc.core.StatementCreatorUtils=OFF

logging.level.net.ttddyy.dsproxy=OFF
logging.level.p6spy=OFF

logging.level.com.zaxxer.hikari=INFO

spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000

spring.datasource.hikari.leak-detection-threshold=30000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

management.metrics.enable.jvm=false

spring.autoconfigure.exclude=org.springframework.boot.actuate.autoconfigure.metrics.JvmMetricsAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration



